import telebot
import random
from time import sleep
bot = telebot.TeleBot('Place_Your_TelegramBot_token')
advices = [
    "Always communicate openly and honestly with your partner.",
    "Spend quality time together and make each other a priority.",
    "Be supportive and understanding of each other's wants and needs.",
    "Work together as a team and make decisions together.",
    "Be respectful of each other's opinions and decisions.",
    "Show appreciation and gratitude towards each other regularly.",
    "Never stop having fun and being playful with each other.",
    "Forgive and let go of grudges to maintain a positive relationship.","Communication is key in any relationship.",
    "Practice active listening when your partner is speaking.",
    "Be honest and transparent in your relationship.",
    "Set clear and reasonable boundaries with your partner.",
    "Show appreciation and gratitude towards your partner regularly.",
    "Learn to compromise and find a middle ground.",
    "Take responsibility for your actions and apologize when necessary.",
    "Practice forgiveness and let go of grudges.",
    "Respect each other's individuality and give each other space.",
    "Prioritize quality time together and keep the spark alive.",
    "Never stop learning and growing as a person and as a couple.",
    "Invest in your relationship through effort and attention.",
    "Encourage and support each other's personal and professional goals.",
    "Learn to handle conflict in a healthy and productive manner.",
    "Be willing to seek help and support from a professional therapist.",
    "Practice open-mindedness and be willing to see things from your partner's perspective.",
    "Be understanding and patient with each other.",
    "Practice empathy and put yourself in your partner's shoes.",
    "Maintain a positive outlook and avoid negativity in your relationship.",
    "Practice giving and receiving affection and love.",
    "Respect each other's opinions and beliefs.",
    "Always keep the lines of communication open.",
    "Focus on finding solutions rather than placing blame.",
    "Be willing to work together to resolve issues.",
    "Set achievable goals as a couple and work towards them together.",
    "Maintain a balance of power in your relationship.",
    "Have fun and enjoy each other's company.",
    "Build trust and foster a strong foundation for your relationship.",
    "Practice good self-care and prioritize your own well-being.",
    "Be flexible and adaptable to change.",
    "Celebrate each other's victories and support each other during challenges.",
    "Maintain a sense of humor and don't take things too seriously.",
    "Allow each other to grow and evolve as individuals.",
    "Be willing to make sacrifices for the sake of your relationship.",
    "Show affection and appreciation for each other regularly.",
    "Be supportive and understanding during difficult times.",
    "Take responsibility for your own happiness and don't rely solely on your partner.",
    "Invest in your personal growth and development as an individual.",
    "Practice mutual respect in all aspects of your relationship.",
    "Be honest about your feelings and emotions.",
    "Practice patience and understanding in dealing with each other's weaknesses.",
    "Take breaks and find time for self-care and personal reflection.",
    "Be willing to try new things and explore new experiences together.",
    "Make quality time for each other a priority.",
    "Practice good communication skills and avoid misunderstandings.",
    "Encourage each other's personal and professional growth.",
    "Be respectful of each other's personal space and boundaries.",
    "Foster a positive and uplifting environment in your relationship.",
    "Be willing to make compromises and find common ground.",
    "Allow each other to express yourselves freely and openly.",
    "Work together to resolve conflicts and disagreements.",
    "Focus on the present moment and enjoy each other's company.",
    "Be understanding and accepting of each other's flaws.",
    "Communication is key in any relationship, including marriage.",
    "Always make time for each other, no matter how busy life gets.",
    "Show appreciation for your partner regularly and express your love for them.",
    "Learn to forgive and let go of grudges and resentment.",
    "Prioritize intimacy and physical affection in your relationship.",
    "Never stop dating and making time for romance.",
    "Be open and honest about your feelings, thoughts, and expectations.",
    "Practice active listening and pay attention to what your partner is saying.",
    "Respect each other's opinions, even if you don't always agree.",
    "Work together as a team to tackle challenges and reach shared goals.",
    "Find common interests and hobbies to share and enjoy together.",
    "Take care of your own personal growth and self-improvement.",
    "Seek support and guidance from a trusted therapist or counselor.",
    "Celebrate each other's victories and successes, no matter how big or small.",
    "Find ways to balance your individual needs and priorities with your shared responsibilities.",
    "Remember to say “I love you” often and show affection regularly.",
    "Set boundaries and stick to them for a healthy and harmonious relationship.",
    "Practice patience, empathy, and understanding towards your partner.",
    "Acknowledge and address any issues or conflicts in a timely and proactive manner.",
    "Make time for self-care and personal fulfillment outside of your relationship.",
    "Invest in the relationship and prioritize your commitment to each other.",
    "Encourage each other's personal and professional growth.",
    "Be open to trying new things and stepping outside of your comfort zones.",
    "Trust and support each other, even in times of uncertainty.",
    "Foster a positive and nurturing environment in your relationship.",
    "Stay connected and maintain a strong emotional bond with your partner.",
    "Keep the romance and excitement alive in your relationship.",
    "Remember to have fun and enjoy each other's company.",
    "Don't be afraid to ask for help or support when needed.",
    "Maintain a healthy and balanced lifestyle for the well-being of both partners.",
    "Show empathy and understanding towards your partner during difficult times.",
    "Take responsibility for your actions and communicate openly and effectively.",
    "Share in household tasks and responsibilities to create a harmonious home life.",
    "Support each other's personal goals and dreams.",
    "Practice gratitude and appreciate the love and support in your relationship.",
    "Create shared memories and experiences together.",
    "Prioritize spending quality time together, both as a couple and as a family.",
    "Keep the spark and passion alive through thoughtful gestures and surprises.",
    "Learn to compromise and make decisions together as a team.",
    "Foster a trusting and open relationship based on honesty and transparency.",
    "Make an effort to stay connected with friends and family for a strong support system.",
    "Create healthy and positive communication habits for a strong relationship.",
    "Don't be afraid to seek professional help or counseling when needed.",
    "Keep the romance alive through regular date nights and intimate moments.",
    "Encourage each other to pursue personal interests and passions.",
    "Seek ways to grow together""I love you more than words can express.",
    "You make my heart skip a beat every time I see you.",
    "I am so grateful to have you in my life.",
    "I cherish every moment spent with you.",
    "You light up my world and bring joy to my life.",
    "You make me want to be a better person.",
    "I can't imagine my life without you.",
    "Every moment with you is special and precious to me.",
    "I love the way you make me feel.",
    "You are my everything.",
    "I love you more than anything else in this world.",
    "You bring happiness and love into my life.",
    "I am so lucky to have you as my girlfriend.",
    "You make every day brighter just by being in it.",
    "I love the sound of your laughter and your smile.",
    "You are my soulmate and I am so grateful to have found you.",
    "I can't wait to spend the rest of my life with you.",
    "You make me feel like the luckiest person in the world.",
    "I love the way you look at me.",
    "You are the best thing that has ever happened to me.",
    "I am so happy to call you mine.",
    "I love your kindness, your laughter, and your beauty.",
    "You complete me in every way.",
    "I love the way you understand me and always know just what to say.",
    "You are my rock and support through everything.",
    "I love the way you love me for who I am.",
    "I am so thankful for your love and support.",
    "You are my everything and I love you with all my heart.",
    "I can't wait to grow old with you and make many more memories.",
    "You bring so much joy and happiness into my life.",
    "I love the way you make me feel when I'm with you.",
    "You are my best friend and my soulmate.",
    "I am so lucky to have you in my life.",
    "I love your laughter, your smile, and your beautiful soul.",
    "You are my one and only love.",
    "I love the way you hold me and make me feel safe.",
    "You make every day better just by being in it.",
    "I love the way you kiss me and the way you touch me.",
    "You are my forever and always.",
    "I am so thankful for all the ways you show me love.",
    "You make me feel like the most important person in the world.",
    "I love the way you always know just what to do to make me happy.",
    "You are my sunshine on a cloudy day.",
    "I am so grateful for your love and your presence in my life.",
    "I love your intelligence, your creativity, and your beautiful spirit.",
    "You are the missing piece to my puzzle.",
    "I am so happy to have found you and to call you my own.",
    "I love the way you always put a smile on my face.",
    "You are my partner in crime and my best friend.",
    "I am so thankful for the love and laughter you bring into my life.",
    "I love the way you make every day an adventure.",
     ]

def hourly_message():
    chat_ids = ['place your chatids in this list']
    # Selecting a random advice from the list
    advice = random.choice(advices)
    for chat_id in chat_ids:
        bot.send_message(chat_id,advice)
    # Sending the message
    
    # Setting timer for the next message
    sleep(86400) # Sleep for 1 Day
    
while True:
    hourly_message()
